Several changes:   - add Config.TagStart to make the cs part of <?cs configurable   - add with command: this works like each but directly instead of     iterating over the children.  Also, non-existance of what you're     pointing at doesn't prevent the execution of the enclosed area   - add the concept of boolean evaluation to match perl and satisfy Dave     Now, || and && force boolean evaluation instead of numeric, and     boolean evaluation implies false is either doesn't exist, 0, "0", ""     if now uses boolean evaluation directly instead of a hack     This DOES CHANGE how some CS templates will render, but it is     probably true that it won't change things that you expected to work     in the past (ie, it changes 'if:Foo || #0' if Foo evaluates to a non-numeric     non-empty string)   - Another "do what I mean" change: in expressions, numeric values     without a # in front of them will be assumed to be numbers, so     'if:1' is the same as 'if:#1'.  To get the old behavior, you need to     use the new "coerce varname" symbol, '$', ie 'if:$1'   - strings can now be specified with single quotes or double quotes

diff --git a/cs/Makefile b/cs/Makefile
--- a/cs/Makefile
+++ b/cs/Makefile
@@ -27,7 +27,7 @@ LIBS += -L$(LIB_DIR) -lneo_cs -lneo_utl # -lefence
 
 TARGETS = $(CS_LIB) $(CSTEST_EXE) $(CSR_EXE) test
 
-CS_TESTS = test.cs test2.cs test3.cs test4.cs test5.cs test6.cs test7.cs test8.cs test9.cs test10.cs test11.cs test12.cs test13.cs test14.cs test15.cs test16.cs test17.cs test18.cs test_var.cs test_paren.cs test_chuck.cs test_trak1.cs test_iter.cs test_each_array.cs test_name.cs
+CS_TESTS = test.cs test2.cs test3.cs test4.cs test5.cs test6.cs test7.cs test8.cs test9.cs test10.cs test11.cs test12.cs test13.cs test14.cs test15.cs test16.cs test17.cs test18.cs test_var.cs test_paren.cs test_chuck.cs test_trak1.cs test_iter.cs test_each_array.cs test_name.cs test_with.cs
 
 all: $(TARGETS)
 
@@ -48,21 +48,34 @@ gold: $(CSTEST_EXE)
 	@for test in $(CS_TESTS); do \
 		rm -f $$test.gold; \
 		./cstest test.hdf $$test > $$test.gold; \
-	done
+	done; \
+	./cstest test_tag.hdf test_tag.cs > test_tag.cs.gold
 	@echo "Generated Gold Files"
 
 test: $(CSTEST_EXE) $(CS_TESTS)
 	@echo "Running cs regression tests"
-	@for test in $(CS_TESTS); do \
+	@failed=0; \
+	for test in $(CS_TESTS); do \
 		rm -f $$test.out; \
 		./cstest test.hdf $$test > $$test.out 2>&1; \
 		diff --brief $$test.out $$test.gold; \
 		return_code=$$?; \
 		if [ $$return_code -ne 0 ]; then \
-		  echo "Failed Regression Test: $$test.out"; \
-		  exit 1; \
+		  echo "Failed Regression Test: $$test"; \
+		  failed=1; \
 		fi; \
-	done
+	done; \
+	rm -f test_tag.cs.out; \
+	./cstest test_tag.hdf test_tag.cs> test_tag.cs.out 2>&1; \
+	diff --brief test_tag.cs.out test_tag.cs.gold; \
+	return_code=$$?; \
+	if [ $$return_code -ne 0 ]; then \
+	  echo "Failed Regression Test: test_tag.cs"; \
+	  failed=1; \
+	fi; \
+	if [ $$failed -eq 1 ]; then \
+	  exit 1; \
+	fi;
 	@touch test
 	@echo "Passed"
 	
