Pick up latest changes from htmlparser. - CL 9106528: Precompute the state table in generate_fsm.py instead of doing it in code. - CL 8795642: Added a simple micro-benchmark so we can measure the performance between diferent CLs. (This CL restructured testdata directory, adding two new directories in it) - CL 8720452: Add a method to return a human readable error message to be displayed in case of parsing errors. - CL 8461682: Track line numbers for error messages and integration with templatelint. Add entityfilter_delete() to the header file. statemachine_reset() for consistency. - CL 8421638: Refactor the FSM generator so it's easier to add more languages, extracting the config file loading logic from the C file generation. Add unit test. (This CL created tools directory and moved generate_fsm.py to it).

diff --git a/trunk/htmlparser/Makefile b/trunk/htmlparser/Makefile
--- a/trunk/htmlparser/Makefile
+++ b/trunk/htmlparser/Makefile
@@ -10,11 +10,19 @@ HTML_SRC = statemachine.c htmlparser.c jsparser.c
 HTML_OBJ = $(HTML_SRC:%.c=%.o)
 HTML_HDR = $(HTML_SRC:%.c=%.h)
 
-HTML_TEST_EXE = test2
-HTML_TEST_SRC = test2.c
-HTML_TEST_OBJ = $(HTML_TEST_SRC:%.c=%.o)
+HTMLPARSER_TEST_EXE = htmlparser_test
+HTMLPARSER_TEST_SRC = htmlparser_test.c
+HTMLPARSER_TEST_OBJ = $(HTMLPARSER_TEST_SRC:%.c=%.o)
 
-TARGETS = $(HTML_LIB)
+JSPARSER_TEST_EXE = jsparser_test
+JSPARSER_TEST_SRC = jsparser_test.c
+JSPARSER_TEST_OBJ = $(JSPARSER_TEST_SRC:%.c=%.o)
+
+STATEMACHINE_TEST_EXE = statemachine_test
+STATEMACHINE_TEST_SRC = statemachine_test.c
+STATEMACHINE_TEST_OBJ = $(STATEMACHINE_TEST_SRC:%.c=%.o)
+
+TARGETS = $(HTML_LIB) test
 
 all: $(TARGETS)
 
@@ -22,13 +30,46 @@ $(HTML_LIB): $(HTML_OBJ)
 	$(AR) $@ $(HTML_OBJ)
 	$(RANLIB) $@
 
+$(HTMLPARSER_TEST_EXE): $(HTMLPARSER_TEST_OBJ) $(HTML_LIB)
+	$(LD) $@ $(HTMLPARSER_TEST_OBJ) $(LDFLAGS) $(HTML_LIB)
+
+$(JSPARSER_TEST_EXE): $(JSPARSER_TEST_OBJ) $(HTML_LIB)
+	$(LD) $@ $(JSPARSER_TEST_OBJ) $(LDFLAGS) $(HTML_LIB)
+
+$(STATEMACHINE_TEST_EXE): $(STATEMACHINE_TEST_OBJ) $(HTML_LIB)
+	$(LD) $@ $(STATEMACHINE_TEST_OBJ) $(LDFLAGS) $(HTML_LIB)
+
 install: all
 	$(NEOTONIC_ROOT)/mkinstalldirs $(DESTDIR)$(cs_includedir)/htmlparser
 	$(INSTALL) -m 644 $(HTML_HDR) $(DESTDIR)$(cs_includedir)/htmlparser
 	$(INSTALL) -m 644 $(HTML_LIB) $(DESTDIR)$(libdir)
 
+test: $(HTMLPARSER_TEST_EXE) $(JSPARSER_TEST_EXE) $(STATEMACHINE_TEST_EXE)
+	@echo "Running HTML parser unit tests"
+	@./$(HTMLPARSER_TEST_EXE) ; \
+	return_code=$$?; \
+	if [ $$return_code -ne 0 ]; then \
+	  echo "Failed Test $(HTMLPARSER_TEST_EXE)"; \
+	  exit 1; \
+	fi;
+	@echo "Running JS parser unit tests"
+	@./$(JSPARSER_TEST_EXE) ; \
+	return_code=$$?; \
+	if [ $$return_code -ne 0 ]; then \
+	  echo "Failed Test $(JSPARSER_TEST_EXE)"; \
+	  exit 1; \
+	fi;
+	@echo "Running Statemachine unit tests"
+	@./$(STATEMACHINE_TEST_EXE) ; \
+	return_code=$$?; \
+	if [ $$return_code -ne 0 ]; then \
+	  echo "Failed Test $(STATEMACHINE_TEST_EXE)"; \
+	  exit 1; \
+	fi;
+	@echo "Passed"
+
 clean:
-	$(RM) *.o
+	$(RM) *.o $(HTMLPARSER_TEST_EXE) $(JSPARSER_TEST_EXE) $(STATEMACHINE_TEST_EXE)
 
 distclean:
 	$(RM) Makefile.depends $(TARGETS) *.o
