Wrap regex init in a mutex if compiled with pthreads Write test for cgi escape functions to verify text_html still works.
TESTED=added test, no test for race condition though

diff --git a/trunk/cgi/Makefile b/trunk/cgi/Makefile
--- a/trunk/cgi/Makefile
+++ b/trunk/cgi/Makefile
@@ -21,7 +21,9 @@ CGICSTEST_OBJ = $(CGICSTEST_SRC:%.c=%.o)
 
 DLIBS += -lneo_cgi -lneo_cs -lneo_utl # -lefence
 
-TARGETS = $(CGI_LIB) $(STATIC_EXE) $(STATIC_CSO) $(CGICSTEST_EXE)
+TARGETS = $(CGI_LIB) $(STATIC_EXE) $(STATIC_CSO) $(CGICSTEST_EXE) test
+
+CGI_CS_TESTS = test_cgi_funcs.cs
 
 all: $(TARGETS)
 
@@ -37,6 +39,35 @@ $(STATIC_CSO): $(STATIC_OBJ) $(DEP_LIBS)
 
 $(CGICSTEST_EXE): $(CGICSTEST_OBJ) $(DEP_LIBS)
 	$(LD) $@ $(CGICSTEST_OBJ) $(LDFLAGS) $(DLIBS) $(LIBS)
+
+## BE VERY CAREFUL WHEN REGENERATING THESE
+gold: $(CGICSTEST_EXE)
+	@for test in $(CGI_CS_TESTS); do \
+		rm -f $$test.gold; \
+		./cgi_cstest ../cs/test.hdf $$test > $$test.gold; \
+	done
+	@echo "Generated Gold Files"
+
+test: $(CGICSTEST_EXE) $(CGI_CS_TESTS) 
+	@echo "Running cgi cs regression tests"
+	@failed=0; \
+	for test in $(CGI_CS_TESTS); do \
+		rm -f $$test.out; \
+		./cgi_cstest ../cs/test.hdf $$test > $$test.out 2>&1; \
+		diff $$test.out $$test.gold 2>&1 > /dev/null; \
+		return_code=$$?; \
+		if [ $$return_code -ne 0 ]; then \
+		  diff $$test.gold $$test.out > $$test.err; \
+		  echo "Failed Regression Test: $$test"; \
+		  echo "  See $$test.out and $$test.err"; \
+		  failed=1; \
+		fi; \
+	done; \
+	if [ $$failed -eq 1 ]; then \
+	  exit 1; \
+	fi;
+	@touch test
+	@echo "Passed"
 
 install: all
 	$(NEOTONIC_ROOT)/mkinstalldirs $(DESTDIR)$(cs_includedir)/cgi
